// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4G4CJ5YCcbQBsE7VRk55XcHbhIvbBKmA',
    appId: '1:914180725286:web:fa29eba4795c295cdf24e7',
    messagingSenderId: '914180725286',
    projectId: 'double-oreo',
    authDomain: 'double-oreo.firebaseapp.com',
    storageBucket: 'double-oreo.firebasestorage.app',
    measurementId: 'G-30FQ55YKT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEMk-P3ag7hccjSOhP2EtZrwyV5bY3V-4',
    appId: '1:914180725286:android:6f5e9d1ba6144ee2df24e7',
    messagingSenderId: '914180725286',
    projectId: 'double-oreo',
    storageBucket: 'double-oreo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7pYkDqlK27dXltLknev3PUEIBuniNebk',
    appId: '1:914180725286:ios:147cb4e863944a01df24e7',
    messagingSenderId: '914180725286',
    projectId: 'double-oreo',
    storageBucket: 'double-oreo.firebasestorage.app',
    iosBundleId: 'com.example.bomji',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7pYkDqlK27dXltLknev3PUEIBuniNebk',
    appId: '1:914180725286:ios:147cb4e863944a01df24e7',
    messagingSenderId: '914180725286',
    projectId: 'double-oreo',
    storageBucket: 'double-oreo.firebasestorage.app',
    iosBundleId: 'com.example.bomji',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4G4CJ5YCcbQBsE7VRk55XcHbhIvbBKmA',
    appId: '1:914180725286:web:05a671d9db39f7cfdf24e7',
    messagingSenderId: '914180725286',
    projectId: 'double-oreo',
    authDomain: 'double-oreo.firebaseapp.com',
    storageBucket: 'double-oreo.firebasestorage.app',
    measurementId: 'G-570FTC82PS',
  );
}
