name: Claude Code Review

# Configuration: Uses service account JSON file for Firebase authentication
# File: .github/pr-agent-21ba8-firebase-adminsdk-fbsvc-73bedacb8b.json
# Macros are fetched from Firebase Database path: macros/

on:
  pull_request_target:
    types: [opened, synchronize, reopened]


jobs:
  claude-review:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      pull-requests: write
      contents: read
    
    # Skip if PR is from a fork to avoid secrets exposure or if it's a draft
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.draft == false

    steps:
      - name: Checkout full repo history
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Set up Python and install dependencies
        run: |
          python3 -m pip install --upgrade pip > /dev/null 2>&1
          pip install firebase-admin anthropic openai > /dev/null 2>&1

      - name: Initialize AI cost tracking
        run: |
          cd .github/scripts && python3 -c "from cost_tracker import initialize_cost_tracking; initialize_cost_tracking()"

      # Uncomment below to test cost tracking functionality
      # - name: Test cost tracking (optional)
      #   run: |
      #     python3 .github/scripts/test_cost_tracking.py

      - name: Fetch configuration macros from Firebase
        id: fetch-macros
        continue-on-error: true
        run: |
          python3 .github/scripts/fetch_macros.py

      - name: Generate diff between base and head (excluding workflow file)
        id: diff
        run: |
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          git fetch origin "$BASE_SHA" "$HEAD_SHA"

          DIFF=$(git diff "$BASE_SHA" "$HEAD_SHA" -- . ':(exclude).github/**')
          echo "diff_b64=$(printf '%s' "$DIFF" | base64 -w0)" >> "$GITHUB_OUTPUT"

          LINE_COUNT=$(echo "$DIFF" | grep -c '^[+-]' || echo "0")
          echo "line_count=$LINE_COUNT" >> "$GITHUB_OUTPUT"

      - name: Check for important changes
        id: check-important
        run: |
          # Get macro values from previous step or use defaults
          IMPORTANT_CHANGE_MARKERS="${{ steps.fetch-macros.outputs.important_change_markers || '#IMPORTANT-CHANGE,#IMPORTANT-CHANGES' }}"
          IMPORTANT_CHANGE_LABELS="${{ steps.fetch-macros.outputs.important_change_labels || 'important change,important changes' }}"
          
          # Check for important change markers in title
          HAS_IMPORTANT_TITLE=false
          if echo '${{ github.event.pull_request.title }}' | grep -q -E "$(echo "$IMPORTANT_CHANGE_MARKERS" | sed 's/,/|/g')"; then
            HAS_IMPORTANT_TITLE=true
          fi
          
          # Check for important change labels
          HAS_IMPORTANT_LABEL=false
          if echo '${{ toJSON(github.event.pull_request.labels.*.name) }}' | grep -q -E "$(echo "$IMPORTANT_CHANGE_LABELS" | sed 's/,/|/g')"; then
            HAS_IMPORTANT_LABEL=true
          fi
          
          # Determine if this is an important change
          IS_IMPORTANT_CHANGE=false
          if [ "$HAS_IMPORTANT_TITLE" = "true" ] || [ "$HAS_IMPORTANT_LABEL" = "true" ]; then
            IS_IMPORTANT_CHANGE=true
          fi
          
          echo "has_important_title=$HAS_IMPORTANT_TITLE" >> "$GITHUB_OUTPUT"
          echo "has_important_label=$HAS_IMPORTANT_LABEL" >> "$GITHUB_OUTPUT"
          echo "is_important_change=$IS_IMPORTANT_CHANGE" >> "$GITHUB_OUTPUT"

      - name: Track architecture changes in Firebase
        id: track-arch
        if: steps.check-important.outputs.is_important_change == 'true'
        continue-on-error: true
        env:
          CHANGES_THRESHOLD: ${{ steps.fetch-macros.outputs.changes_threshold || '5' }}
          DIFF_B64: ${{ steps.diff.outputs.diff_b64 }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPOSITORY: ${{ github.repository }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          python3 .github/scripts/track_architecture.py

      - name: Summarize architecture if needed
        if: steps.check-important.outputs.is_important_change == 'true' && steps.track-arch.outcome == 'success' && contains(steps.track-arch.outputs.should_summarize, 'true')
        continue-on-error: true
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          CHANGES_THRESHOLD: ${{ steps.fetch-macros.outputs.changes_threshold || '5' }}
          REPOSITORY: ${{ github.repository }}
          SHOULD_SUMMARIZE: 'true'
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python3 .github/scripts/summarize_architecture.py
          
      - name: Fetch architecture context from Firebase
        id: fetch-context
        continue-on-error: true
        env:
          CHANGES_THRESHOLD: ${{ steps.fetch-macros.outputs.changes_threshold || '5' }}
          REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python3 .github/scripts/fetch_firebase_context.py

      - name: Choose model based on line count and labels
        id: choose-model
        run: |
          THRESHOLD=${{ steps.fetch-macros.outputs.line_threshold || '200' }}
          LINES=${{ steps.diff.outputs.line_count }}
          HAS_IMPORTANT_LABEL=${{ steps.check-important.outputs.has_important_label }}
          HAS_IMPORTANT_TITLE=${{ steps.check-important.outputs.has_important_title }}
          
          # Set outputs for use in next steps
          echo "has_important_label=$HAS_IMPORTANT_LABEL" >> "$GITHUB_OUTPUT"
          echo "has_important_title=$HAS_IMPORTANT_TITLE" >> "$GITHUB_OUTPUT"
          echo "line_threshold=$THRESHOLD" >> "$GITHUB_OUTPUT"
          
          # Model selection logic:
          # 1. If has important label or title marker -> use Claude
          # 2. If no label/title but exceeds threshold -> use Claude
          # 3. Otherwise -> use o3-mini
          if [ "$HAS_IMPORTANT_LABEL" = "true" ] || [ "$HAS_IMPORTANT_TITLE" = "true" ]; then
            echo "model=claude-sonnet-4-20250514" >> "$GITHUB_OUTPUT"
            echo "model_comment=This response was generated by Claude 4 Sonnet (important changes detected)." >> "$GITHUB_OUTPUT"
            echo "Using Claude due to important changes (label: $HAS_IMPORTANT_LABEL, title: $HAS_IMPORTANT_TITLE)"
          elif [ "$LINES" -gt "$THRESHOLD" ]; then
            echo "model=claude-sonnet-4-20250514" >> "$GITHUB_OUTPUT"
            echo "model_comment=This response was generated by Claude 4 Sonnet (large diff detected)." >> "$GITHUB_OUTPUT"
            echo "Using Claude due to large diff ($LINES lines > $THRESHOLD threshold)"
          else
            echo "model=o3-mini" >> "$GITHUB_OUTPUT"
            echo "model_comment=This response was generated by o3 mini." >> "$GITHUB_OUTPUT"
            echo "Using o3-mini for small diff ($LINES lines <= $THRESHOLD threshold)"
          fi

      - name: Call AI for code review
        id: ai-review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DIFF_B64: ${{ steps.diff.outputs.diff_b64 }}
          MODEL: ${{ steps.choose-model.outputs.model }}
          HAS_IMPORTANT_LABEL: ${{ steps.choose-model.outputs.has_important_label }}
          LINE_THRESHOLD: ${{ steps.choose-model.outputs.line_threshold }}
          ARCHITECTURE_CONTEXT_B64: ${{ steps.fetch-context.outputs.context_b64 }}
        run: |
          python3 .github/scripts/ai_review.py 2>/tmp/ai_review_debug.log

      - name: Display AI costs so far
        if: always()
        run: |
          echo "=== AI COST CHECKPOINT AFTER REVIEW ==="
          python3 .github/scripts/display_costs.py

      - name: Post line-by-line comments on PR
        env:
          REVIEW_TEXT: ${{ steps.ai-review.outputs.review_b64 }}
          MODEL_COMMENT: ${{ steps.choose-model.outputs.model_comment }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          python3 .github/scripts/post_comments.py

      - name: Upload AI response as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ai-response-output
          path: |
            /tmp/ai_response.txt
            /tmp/line_comment.json
            /tmp/summary_comment.json
            /tmp/ai_costs.json
            /tmp/ai_cost_summary.txt
          retention-days: 7

      - name: Finalize AI cost tracking and display summary
        id: cost-summary
        if: always()
        run: |
          echo "=== FINAL AI COST SUMMARY ==="
          cd .github/scripts && python3 -c "from cost_tracker import finalize_cost_tracking; finalize_cost_tracking()"
